# Generated by Django 5.0.14 on 2025-08-04 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager_user", "0002_alter_employe_adresse_departement_service_poste"),
    ]

    operations = [
        migrations.AddField(
            model_name="employe",
            name="departement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="Manager_user.departement",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="departement",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departements_responsables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
