# Generated by Django 5.0.14 on 2025-08-05 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager_user", "0003_employe_departement_alter_departement_responsable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Manager_user.departement",
            ),
        ),
    ]
