# Generated by Django 5.0.14 on 2025-08-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager_user", "0004_alter_employe_departement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employe",
            name="adresse",
        ),
        migrations.RemoveField(
            model_name="employe",
            name="prenom",
        ),
        migrations.RemoveField(
            model_name="employe",
            name="telephone",
        ),
        migrations.AlterField(
            model_name="employe",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("chief", "Chief"),
                    ("plant manager", "Plant Manager"),
                    ("manager", "Manager"),
                    ("ingenieur", "Ingénieur"),
                    ("technicien", "Technicien"),
                ],
                max_length=20,
            ),
        ),
    ]
