# Generated by Django 5.0.14 on 2025-09-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager_user", "0005_remove_employe_adresse_remove_employe_prenom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("chief", "Chief"),
                    ("plant manager", "Plant Manager"),
                    ("manager", "Manager"),
                    ("ingenieur", "Ingénieur"),
                    ("technicien", "Technicien"),
                    ("coordinateur", "Coordinateur"),
                ],
                max_length=20,
            ),
        ),
    ]
