# Generated by Django 5.0.14 on 2025-08-05 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Manager_user", "0003_employe_departement_alter_departement_responsable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "unite",
                    models.CharField(help_text="ex: %, Kg, unités…", max_length=50),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="Manager_user.departement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KpiTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur_cible", models.FloatField()),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_creation", models.DateField(auto_now_add=True)),
                (
                    "kpi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target",
                        to="Manager_KPI.kpi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KpiValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.FloatField()),
                ("date_saisie", models.DateTimeField(auto_now_add=True)),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valeurs",
                        to="Manager_KPI.kpi",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
