# Generated by Django 5.0.14 on 2025-08-06 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager_KPI", "0001_initial"),
        ("Manager_user", "0005_remove_employe_adresse_remove_employe_prenom_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="kpitarget",
            old_name="valeur_cible",
            new_name="valeur_objectif",
        ),
        migrations.RenameField(
            model_name="kpivalue",
            old_name="date_saisie",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="kpitarget",
            name="kpi",
        ),
        migrations.RemoveField(
            model_name="kpivalue",
            name="kpi",
        ),
        migrations.RemoveField(
            model_name="kpivalue",
            name="utilisateur",
        ),
        migrations.AddField(
            model_name="kpitarget",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpitarget",
            name="date_validite",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="kpitarget",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Manager_user.departement",
            ),
        ),
        migrations.AddField(
            model_name="kpitarget",
            name="titre",
            field=models.CharField(default="Objectif automatique", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpivalue",
            name="cible",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Manager_KPI.kpitarget",
            ),
        ),
        migrations.AddField(
            model_name="kpivalue",
            name="employe",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="kpitarget",
            name="frequence",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                max_length=20,
            ),
        ),
    ]
