# Generated by Django 5.0.14 on 2025-08-06 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager_KPI", "0002_rename_valeur_cible_kpitarget_valeur_objectif_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="kpitarget",
            old_name="date_validite",
            new_name="valid_from",
        ),
        migrations.RemoveField(
            model_name="kpi",
            name="description",
        ),
        migrations.RemoveField(
            model_name="kpitarget",
            name="date_creation",
        ),
        migrations.RemoveField(
            model_name="kpitarget",
            name="departement",
        ),
        migrations.RemoveField(
            model_name="kpitarget",
            name="frequence",
        ),
        migrations.RemoveField(
            model_name="kpitarget",
            name="titre",
        ),
        migrations.RemoveField(
            model_name="kpivalue",
            name="cible",
        ),
        migrations.AddField(
            model_name="kpi",
            name="aggregation_type",
            field=models.CharField(
                choices=[("sum", "Somme"), ("avg", "Moyenne")],
                default="somme",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpi",
            name="date_measured",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="kpi",
            name="date_modification",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="kpi",
            name="frequence",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="daily",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpitarget",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kpitarget",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpitarget",
            name="kpi",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target",
                to="Manager_KPI.kpi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpitarget",
            name="target_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="kpitarget",
            name="valid_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kpivalue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kpi_values_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kpivalue",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="kpivalue",
            name="kpi",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Manager_KPI.kpi",
            ),
        ),
        migrations.AlterField(
            model_name="kpivalue",
            name="employe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kpi_values_enregistrees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
