# Generated by Django 5.0.14 on 2025-09-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager_KPI", "0003_rename_date_validite_kpitarget_valid_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="unite",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="ShiftReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("MATIN", "Matin"),
                            ("SOIR", "Soir"),
                            ("NUIT", "Nuit"),
                        ],
                        max_length=10,
                    ),
                ),
                ("effectif", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpi_shift_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "shift", "sup"],
            },
        ),
        migrations.CreateModel(
            name="AbsenceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ABS_NON_JUST", "Absent non justifié"),
                            ("MIS_A_PIED", "Mis à pied"),
                            ("CONGE", "Congé"),
                            ("MALADIE", "Maladie"),
                            ("MATERNITE", "Maternité (MAT)"),
                            ("AUTORISE", "Autorisé"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("qty", models.PositiveIntegerField()),
                ("autre_motif", models.CharField(blank=True, max_length=120)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="Manager_KPI.shiftreport",
                    ),
                ),
            ],
            options={
                "ordering": ["report_id", "type"],
            },
        ),
        migrations.AddConstraint(
            model_name="shiftreport",
            constraint=models.UniqueConstraint(
                fields=("date", "shift", "sup"), name="uniq_shiftreport_date_shift_sup"
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftreport",
            constraint=models.CheckConstraint(
                check=models.Q(("effectif__gte", 1)),
                name="ck_shiftreport_effectif_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="absenceline",
            constraint=models.CheckConstraint(
                check=models.Q(("qty__gte", 1)), name="ck_absenceline_qty_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="absenceline",
            constraint=models.UniqueConstraint(
                fields=("report", "type"), name="uniq_line_per_type_per_report"
            ),
        ),
    ]
