# Generated by Django 5.0.14 on 2025-09-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager_KPI", "0004_alter_kpi_unite_shiftreport_absenceline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kpitarget",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="kpitarget",
            name="kpi",
        ),
        migrations.RemoveField(
            model_name="kpivalue",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="kpivalue",
            name="employe",
        ),
        migrations.RemoveField(
            model_name="kpivalue",
            name="kpi",
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="abs_non_justifie",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="autorise",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="autre",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="conge",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="maladie",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="maternite",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shiftreport",
            name="mis_a_pied",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="AbsenceLine",
        ),
        migrations.DeleteModel(
            name="KpiTarget",
        ),
        migrations.DeleteModel(
            name="KpiValue",
        ),
    ]
