# Generated by Django 5.0.14 on 2025-09-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Manager_KPI",
            "0005_remove_kpitarget_created_by_remove_kpitarget_kpi_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftreport",
            name="autre_motif",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
