# Generated by Django 5.0.14 on 2025-09-11 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager_KPI", "0006_shiftreport_autre_motif"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShiftReport",
            new_name="Absence",
        ),
        migrations.RemoveConstraint(
            model_name="absence",
            name="uniq_shiftreport_date_shift_sup",
        ),
        migrations.RemoveConstraint(
            model_name="absence",
            name="ck_shiftreport_effectif_gte_1",
        ),
        migrations.AddConstraint(
            model_name="absence",
            constraint=models.UniqueConstraint(
                fields=("date", "shift", "sup"), name="uniq_absence_date_shift_sup"
            ),
        ),
        migrations.AddConstraint(
            model_name="absence",
            constraint=models.CheckConstraint(
                check=models.Q(("effectif__gte", 1)), name="ck_absence_effectif_gte_1"
            ),
        ),
    ]
